### ISSUE TITLE
Unable to import Pegasos module (because atleast2d_or_csr is absent)

### ISSUE THREAD

**Issue by ChrisBg** [ejlb/pegasos#2]
Hi Ejlb,

I' d like to use your pegasos library but when I try to import pegasos in python I obtain an ImportError which is the following:

Python 2.7.9 |Anaconda 2.2.0 (64-bit)| (default, Mar  9 2015, 16:20:48) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://binstar.org

> > > import pegasos
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > >   File "pegasos/**init**.py", line 18, in <module>
> > >     from .models import SVMPegasosBase, LogisticPegasosBase
> > >   File "pegasos/models.py", line 20, in <module>
> > >     from .base import PegasosBase
> > >   File "pegasos/base.py", line 21, in <module>
> > >     from sklearn.utils import atleast2d_or_csr
> > > ImportError: cannot import name atleast2d_or_csr

I'm using the current version of scikit learn (0.16.1) in which atleast2d_or_csr isn't available.

Please would you have an idea or a solution ?

Thank you in advance,

Chris

**Comment by davidfarrugia** [comment]
use `check_array` instead.

**Comment by xiemark** [comment]
pip install --user scikit-learn==0.13.1
